### ISSUE TITLE
Adding vanilla JS modules results in Vite error

### ISSUE THREAD

**Issue by franktopel** [stefanfrede/11st-starter-kit#333]
I may be misunderstanding what this project is meant to achieve.

I was looking for a setup that combines the power and development convenience of Vite.js with the static site generation capabilities of 11ty.

As such, I've tried the following:

1. Check out your repo.
2. Remove tailwind.css and Alpine.js as I'm interested in a setup that does not suggest any frameworks/libs.
3. Add a new folder and file: `src/js/components/foo-bar/foo-bar.js`.
4. Import this component in `main.js` using `import './js/components/foo-bar/foo-bar.js';`.

This results in

```
21:37:00 [vite] Internal server error: Failed to resolve import "./js/components/foo-bar/foo-bar.js" from "_site/main.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/connexo/Sites/11st-starter-kit/_site/main.js
  1  |  import './styles/main.css';
  2  |  import './js/components/foo-bar/foo-bar.js';
     |          ^
  3  |
  4  |  const env = document.querySelector('body').dataset.env;
      at formatError (/Users/connexo/Sites/11st-starter-kit/node_modules/vite/dist/node/chunks/dep-f5552faa.js:36769:46)
      at TransformContext.error (/Users/connexo/Sites/11st-starter-kit/node_modules/vite/dist/node/chunks/dep-f5552faa.js:36765:19)
      at normalizeUrl (/Users/connexo/Sites/11st-starter-kit/node_modules/vite/dist/node/chunks/dep-f5552faa.js:73703:26)
      at async TransformContext.transform (/Users/connexo/Sites/11st-starter-kit/node_modules/vite/dist/node/chunks/dep-f5552faa.js:73843:57)
      at async Object.transform (/Users/connexo/Sites/11st-starter-kit/node_modules/vite/dist/node/chunks/dep-f5552faa.js:36985:30)
      at async doTransform (/Users/connexo/Sites/11st-starter-kit/node_modules/vite/dist/node/chunks/dep-f5552faa.js:52060:29) (x2)
```

Is this project not set up to combine the blazing fast HMR capabilities of Vite with the raw SSG power of 11ty?

Please explain how to properly set up vanilla JS imports within this project.

**Comment by stefanfrede** [comment]
I only use Vite.js to have a dev server for working with Eleventy and to build for "production".

Have you tried [Astro](https://astro.build/)? I guess that would be a better fit for you.
