### ISSUE TITLE
"RangeError: Maximum call stack size exceeded" when npm run dev WSL2

### ISSUE THREAD

**Issue by Sercurio** [stefanfrede/11st-starter-kit#334]
I'm using Debian WSL2 on Windows 10.

What I did:
* clone the repo
* npm run install
* npm run dev

The error I got:
```
$ npm run dev

> 11st-starter-kit@2.0.0 predev
> run-s clean


> 11st-starter-kit@2.0.0 clean
> rimraf _site


> 11st-starter-kit@2.0.0 dev
> cross-env NODE_ENV=development run-p dev:*


> 11st-starter-kit@2.0.0 dev:vite
> npx vite


> 11st-starter-kit@2.0.0 dev:eleventy
> npx @11ty/eleventy --watch

error when starting dev server:
RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at interpolate (/home/louis/Sites/11st-starter-kit/node_modules/vite/dist/node/chunks/dep-f5552faa.js:74589:28)
    at /home/louis/Sites/11st-starter-kit/node_modules/vite/dist/node/chunks/dep-f5552faa.js:74607:17
    at Array.reduce (<anonymous>)
    at interpolate (/home/louis/Sites/11st-starter-kit/node_modules/vite/dist/node/chunks/dep-f5552faa.js:74591:20)
    at /home/louis/Sites/11st-starter-kit/node_modules/vite/dist/node/chunks/dep-f5552faa.js:74607:17
    at Array.reduce (<anonymous>)
    at interpolate (/home/louis/Sites/11st-starter-kit/node_modules/vite/dist/node/chunks/dep-f5552faa.js:74591:20)
    at /home/louis/Sites/11st-starter-kit/node_modules/vite/dist/node/chunks/dep-f5552faa.js:74607:17
    at Array.reduce (<anonymous>)
ERROR: "dev:vite" exited with 1.
```

Thanks.

**Comment by stefanfrede** [comment]
I have to look into this.

**Comment by stefanfrede** [comment]
Sadly I don't know how to reproduce this error.

Is this happening consistently?
